### ISSUE TITLE
Can only install on windows (python)

### ISSUE THREAD

**Issue by NicklasTegner** [synthizer/synthizer#15]
Hi.

Right now, on pypi, wheels only exists for Windows, and no source distribution is published so it's impossible to install on an unsupported platform.
Is this by design, or what is the horizon on getting either wheels for the other platforms, or also publishing a source distribution?

**Comment by camlorn** [comment]
If you have the library building on other platforms now, I can bump the priority of getting the Python distribution working with it, but the library can't (and shouldn't) build as part of the Python source distribution as-is and the blocker here is actually support for other platforms in the first place.  I will tackle non-Windows builds after reverb.

Also, you can clone the repository and build it that way.  Effectively you'd have to no matter what anyhow, since a source distribution on Pypi isn't going to include Synthizer itself.

**Comment by camlorn** [comment]
I'm starting to explore what has to happen here.  To track more general Linux support see #1, but Python unfortunately has unique problems.  I think that in essence the best we can do here is to upload a source release to Pypi and require that you already have a pre-built (and compatible) Synthizer somewhere else, and under that assumption I'll do some looking to at least find out what has to happen to deal with version conflicts in what is still a fast-moving library.

As an overview of the problem, there's no even remotely stable way to call cmake from setup.py (at least as far as I know).  Manyliux1 doesn't appear to have good support for libstdc++, as in the "here are some workarounds but if you get them wrong you crash if someone else uses C++ and gets it wrong" fun (for an example, see [this comment](https://github.com/pypa/auditwheel/issues/125#issuecomment-606775244)).  The list of blockers probably goes on for a while after that but the only thing I can think of as any sort of solution is the proposal in #18 which also has another set of problems around getting setuptools to play nice, though fortunately that's a more reasonable set.  Regardless I would rather avoid ad-hoc vendoring strategies unless there's going to be more impact than just Python on Linux.

Would be curious to hear what would work for your case specifically.  It's clearer what needs to happen on Windows and Mac here, being as those have more official toolchain/versioning policies.  Are you wanting to redistribute binaries?  If so, what requirements do they need to meet?

**Comment by NicklasTegner** [comment]
> Are you wanting to redistribute binaries? If so, what requirements do they need to meet?

As for what requirements I don't really know.
I'm coming from wanting to use synthizer through the python binding, so I'm asuming as a python developer, that when I do

pip install synthizer

The python module "synthizer" and everything else needed get's downloaded from pypi and optionally builded.
One way I could see it working, is moving the python binding to another repository, something like synthizer/python and then use GitHub actions to automatically build synthizer and publish to pypi (on all platforms) whenever a condition is met.

For easy management of python packages, you might want to take a look at [poetry](https://python-poetry.org/).

But essentially, when using synthizer in a project, I'm expecting it to have the necessary runtime files bundled (dlls on windows, dylib on macand so on), so I can develop it, and when packaging it with some like PyInstaller, they (the lib files) get bundled with too, so my end users can run my application / game / whatever too.

**Comment by camlorn** [comment]
That literally can't work on Linux irregardless of if it's Python or not, unless you've got additional constraints in mind.  I was hoping you knew more about this than me.  On Windows or Mac, you ask the official Microsoft/Apple tools to build your stuff and you get a thing that can be redistributed, but for Linux you have to pick a subset of stuff yourself and there's no one-size-fits-all answer.  In particular, whether you use synthizer or not, I doubt that pyinstaller can produce apps that just work for most people unless you're already paying attention to this stuff.  End users may end up needing to `apt install` or whatever.  I know that there are some solutions for this out there, I just don't know the first thing about them, so it's very hard for me to determine how to give you a useful binary.

Python doesn't vendor libraries.  When you pip install thing on Windows or Mac, you get a wheel instead of a source distribution, which contains the binaries that the developer built for you.  This is how most major Python packages are published.  Unfortunately for Linux, you have to either use manylinux1, which mandates pre-C++14 C++, or you have to use PEP 600, which doesn't even address libstdc++ at all.  For most packages on Linux which require non-Python libraries, you install them first with apt then setup.py links against them when building the C extension.  In practice, the typical way of doing what we're doing here is something to the effect of:

```
git clone git@github.com:synthizer/synthizer
cd synthizer
mkdir build
cd build
cmake ..
make
make install
pip install synthizer
```

Where for stable libraries you replace most of that with `apt install synthizer` or whatever.  But obviously we're a long way from having Synthizer in the package repositories.

If you want better, we need to put some sort of additional constraint on the problem beyond "is Linux", because "is Linux" covers a *lot* of ground here.

**Comment by NicklasTegner** [comment]
From doing a quick googleing, it seems you indeed can get python to build the library on install.
It would go something like the developer having to apt install the dependencies to compile synthizer, then pip install synthizer, that would then download a source distribution that would build synthizer for you and put it where the python library could find it (which would also solve the PyInstaller error).
Because in that case, when build your app (with PyInstaller) you would use CI systems that would build them for multiple set of os's (if needed)

My search turned up this, which gives multiple solutins of solving the issue at hand (on linux specifically)
https://stackoverflow.com/questions/47360113/compile-c-library-on-pip-install
https://stackoverflow.com/questions/24146840/how-do-i-package-for-distribution-a-python-module-that-uses-a-shared-library
https://stackoverflow.com/questions/45121352/how-to-include-a-shared-c-library-in-a-python-package

**Comment by camlorn** [comment]
Skimming your links (I only read the top answer, if there's something more specific you want to propose please do so, but in general I promise that I've googled):

- The first one doesn't seem to be better than asking a user to build the library themselves, if they're going to have to go as far as finding our readme or whatever in order to install a bunch of stuff.
- The second one is about maintaining a second build system, essentially.  We aren't just a few files and compile flags, so that's basically #18.
- The third one is "use manylinux" which I already said we fundamentally can't do without hacks.

I'll time box investigating whether or not getting something kind of hacky with CMake working can be done easily but anticipate that this can't work on Windows because Python extensions don't build from inside the MSVC shell.  If I'm going to go through the trouble of making Python build the extension from scratch, I want the solution for that to be cross platform.  I'm not willing to take on the maintenance burden of maintaining a parallel build system unless other language bindings are really interested in #18, and Nolan already said it won't help much with Rust.  We'll see what happens, but this is starting to brush up against the thing where I don't have enough bandwidth to do everything we might want me to do.

**Comment by camlorn** [comment]
To be clear, Python will work on Linux.  We're almost there now.  It may just not be "Synthizer downloads the repository and builds it for you" working in the end.

**Comment by camlorn** [comment]
You can now `pip install synthizer` on Linux against Python 3, assuming GCC or Clang 9 as the system C compiler.  The only external dependency is `git`.  Long story short, the Python science people have a hard to google for thing called scikit-learn which they've been using for CMake, and they've even gone so far as to produce packages that know how to install CMake into temporary virtualenvs created by Pip for building wheels.

I've tested on Ubuntu 20.10, as far as getting audio output.  Closing this out.  Feel free to raise issues as you find them, or to reopen if something is fundamentally broken, but this should be good now.
