### ISSUE TITLE
synthizer.PannedSource is silent

### ISSUE THREAD

**Issue by chrisnorman7** [synthizer/synthizer#16]
Hi,
Not sure if this just hasn't been implemented yet or not, but using synthizer.PannedSource is silent.

Code to test:

``python
from time import sleep
from synthizer import Context, initialized, BufferGenerator, Buffer, PannedSource, DirectSource

with initialized():
    c = Context()
    b = Buffer.from_stream('file', 'sound.wav')
    s = PannedSource(c)
    d = DirectSource(c)
    g = BufferGenerator(c)
    g.buffer = b
    g.looping = True
    s.add_generator(g)
    sleep(5)
```

If you change the source you're adding the generator to it works.

I feel like we've spoken about this before, so sorry if I'm rehashing old ground. I did search the issues, and my emails first.

In case you need it, you can download the sound I used [here](https://www.dropbox.com/t/00ICZ8WVvCc4wi43).

**Comment by camlorn** [comment]
No, it's probably not old ground.  And it should be implemented as well.  I've been refactoring the guts of those for a bit now, and I suspect that I just missed something when doing that.  I'll get back to you on this.

**Comment by chrisnorman7** [comment]
That's OK no worries.

Thanks for the info.

Take care,

Chris Norman

**Comment by camlorn** [comment]
This is now marked as closed because GitHub doesn't have a "maybe fixes" keyword or anything, but if that's not actually the case, let me know.  Release 0.7.5 is running through CI now.  You're one of the people actively using this though, so if you could take the time to drop it into one of your projects and tell me if the release overall explodes or who knows what else, that'd be great.

The detailed technical explanation of what happened here:

- Source3D didn't properly call the superclass, which meant that PannedSource wouldn't initialize the panner lane.
- PannedSource, if it did initialize properly, didn't flip a boolean to tell itself that it did initialize properly.
- Therefore, going through Source3D would always assign it to lane 0, but going through pannedSource would assign it to lane 1, because it would think that the panning strategy changed.
- Bitsets `.get` method then had a comparison to determine if a bit in the bitset was set, which only worked for bits at multiples of 8.
- HrtfPanner uses that for change tracking, to tell if it should recompute the HRIR, which starts out as a zero-initialized array. But it claims that nothing changed, so the HRIR stays as a zero-initialized array.
- Then we convolve audio with that arrray, handily outputting zero.

Unfortunately fixing the bitset probably introduces other weirdness as well as fixing other as-yet-unfound bugs, so we'll see what happens I suppose.

**Comment by chrisnorman7** [comment]
Thanks for affecting a fix so quickly.

So I've tested it, and it's working, but how do the numbers work?

I seem to have a range from 0 to 360, but I'm unclear as to what the
numbers do.  suspect that's more my lack of maths than your code though, so
if it's just a google away, please let me know.
Take care,

Chris Norman

**Comment by camlorn** [comment]
You probably want to use panning_scalar if you want to just be able to set it to left or right (in that case -1 is left, 1 is right).

The angles match up with the HRTF dataset.  I thought I documented the coordinate system somewhere, but basically 0 is straight ahead, 90 is right, 180 is back, 270 is left.  But panning_scalar is probably easier for most use cases where you aren't driving a Source3d.

**Comment by chrisnorman7** [comment]
OK, that works great.

Only slight bug: When you first create a `PannedSource` instance,
`panning_scalar` is set to `05`, rather than `0`.

Other than that, works perfectly. Thank you.

Take care,

Chris Norman
