### ISSUE TITLE
Rust needs `set(CMAKE_MSVC_RUNTIME_LIBRARY "MultiThreadedDLL")`, best way to achieve?

### ISSUE THREAD

**Issue by ndarilek** [synthizer/synthizer#19]
Had a major breakthrough with the Rust bindings today. Long story shorter, my building of these as a shared library to work around the issues I reported on audiogames.net a while back was an ugly hack. It built a synthizer.dll which had to be located with the executable, and was creating various issues--see those old posts for many of the errors. I kept adding /md in at various places since that was supposed to be the parameter to fix those, but it never seemed to take no matter where I added it. Fast forward to today, after 6 or so hours fighting to get Synthizer statically linking, and I eventually figure out that what I need is:

```
# We always use MultiThreaded, until I can figure out Python setuptools runtime picking options.
#set(CMAKE_MSVC_RUNTIME_LIBRARY "MultiThreaded$<$<CONFIG:Debug>:Debug>")
set(CMAKE_MSVC_RUNTIME_LIBRARY "MultiThreadedDLL")
```

Problem gone. My Synthizer Rust library links statically into Bevy, and no longer needs a synthizer.dll colocated with the executable. Previously things worked when I was just building Synthizer examples, but Bevy seems to pull in some native dependency for working with shaders, and I guess that conflicted with your default of "MultiThreaded".

Is it possible for the Rust bindings to opt into `set(CMAKE_MSVC_RUNTIME_LIBRARY "MultiThreadedDLL")`? Should passing it to `-D` work? It doesn't seem to be, so either I need a different way or my buildscript is broken.

Thanks.

**Comment by camlorn** [comment]
I'm not sure here, but it's on my list of things to fight. I'll try to get you an answer this weekend.

**Comment by ndarilek** [comment]
I've found that if I comment out `# set(CMAKE_MSVC_RUNTIME_LIBRARY "MultiThreaded")` in CMakeLists.txt, I can indeed set it from the command line in build.rs and it works. No more obnoxious link errors using the crate in a complex project with other native dependencies.

Would recommend spending the time to build these tweaks into setuptools and removing them from the generic buildscript, even if it's a slower process. I probably lost close to 18 hours fighting with this one issue with the time spent yesterday plus my struggles a couple months back.

Thanks.

**Comment by camlorn** [comment]
Yeah the thing is, setuptools hates us all and isn't documented half the time.  If I'd realized just how much time you were spending on it I'd have bumped this up my list--in general runtime conflicts are common on Windows, so I just assumed you knew at least in general what was going on.  There's a reason I punted the Synthizer side until later.

I don't know if we can get Python building the extension on Windows at all without something like #18, but at this point that's also on my list for this weekend.  I don't know what I'll actually get to though: I was supposed to have a Linux VM by now but coming back from vacation is a great way to have work consume all your time.

**Comment by ndarilek** [comment]
Is it just a matter of adding either /md or /mt to extra_compile_args in 
setup.py? I'm looking through the setup.py and obvious scripts I'm 
finding for where setuptools calls into cmake. That seems like it'd be 
the obvious place to set this option, but not finding that makes me 
wonder if the option might be removed entirely from CMakeLists.txt so 
individual bindings can set it as needed?


If this is something that I could fix by banging my head against a build 
system for an hour or two and saving you the trouble, I'm willing to do 
that if you can point me to where in the docs or build system I'm likely 
to be intervening.


Thanks.

**Comment by camlorn** [comment]
Doing what you need for this issue is fine, in the sense that it should take me like 20 minutes at most tonight or tomorrow.

Getting Python to clone the repo and build it on Windows is not fine, because Windows has no concept whatsoever of a system C++ compiler and CMake will grab any version of VC++ that it can unless you're really careful, even if the one we wanted was installed.  Also because no system C compiler, Python uses a different VC++ version for itself depending on the version of Python, rather than being compiled by your distro maintainer.  And again, because Windows, no C++ ABI compatibility or anything like that either.  The Rust crate for CMake is handling all of this for you combined with the fact that Rust compiles on your machine, but most of the higher level languages have some combination of these problems.  Since Python and most of the rest of them have no equivalent to Rust's CMake package that encodes the logic for their internal build a C extension tooling, the asks around "can you just have Python download and build it" have exactly the scope you might expect from this description: either I'm maintaining a whole library with a bunch of logic in it to do the equivalent of `git clone && cmake`, it's held together by prayer and good wishes, or both.  The final answer is to probably have it download itself on Linux and mac, then just have it print some sort of error on Windows and be like "sorry, use a wheel" or something.

#18 is off the table because stuff in #1 is going to require the full power of CMake, but if you're wondering why #18 was on the table in the first place--well, see above.

**Comment by camlorn** [comment]
You will possibly need `-DCMAKE_MSVC_RUNTIME_LIBRARY=bla` at the CMake command line.  Note that if this is the case, it's possible that not everyone is going to need the same value, even though it's Rust.  Consequently, you'll want to look into whether or not you can expose that, possibly as a crate feature.  A lot of people (including myself) will build against the static CRT where possible in order to avoid needing to distribute runtime dependencies.

feel free to reopen if this didn't fix it.
