### ISSUE TITLE
Implement an event system

### ISSUE THREAD

**Issue by ahicks92** [synthizer/synthizer#21]
Exactly what it says.  It'll probably be something to the effect of:

```
struct Event {
    union { ... } payload;k
    int type;
};

syz_ErrorCode syz_getEvent(syz_Handle context, int *got, struct Event *evt);
```

backed by a lockfree queue, and filtered so that anything that gets deleted before you grab the event doesn't show up.  The C API will probably in practice be more complicated.   We can expose this in Python as an iterator and I think that can work for Rust too.

CC @chrisnorman7.

**Comment by chrisnorman7** [comment]
Sounds good, not that I understand much of what's going on in your C++.

Why an iterator out of interest? Would something like

```python
def on_done():
    print('Completed.')
generator.on_done = on_done
```

Or even more pythonically:

```python
@generator.register_event('on_done')
def _():
    print('Done.')
```

Absolutely understand if it's easier to implement as an iterator though.

**Comment by camlorn** [comment]
So first, this is a C library.  While the Python bindings are convenient, at the end of the day the point of them is to expose a bunch of C functionality to you, not to be the end-all solution.  Event decorators or similar kind of belong in something like Earwax.

But as for why Synthizer isn't using callbacks:

- In C and most lower level languages, using callbacks is a very special sort of hell where good programmers go to die, at least for smaller programs.
- Anything larger is going to probably already have some sort of event system they'll want to integrate us with.
- Lots of things like SDL work the same way as I'm proposing, so it's similar.

But the really fun point is: suppose Synthizer does expose callbacks.  When do they run?  how?  In Python, you also have the GIL which is a cost you'd pay for every event, but the real question is whether or not you're going to be getting callbacks in the middle of a game tick or not.  SO the right answer ends up being that you call some sort of function that runs all the pending events, which is almost the same thing as just making you iterate them with the added disadvantage of being less flexible.  But that brings us to the next question: what if you need to stop early because you've run out of time and need to run the next tick of your game?  It just in general turns into a scheduling nightmare for anything that's not a trivial app.

**Comment by chrisnorman7** [comment]
That's fine mate. Thank you for the explanation.

Take care,

Chris Norman

**Comment by Keithcat1** [comment]
Could you add a way to directly check if a generator is done playing for example? It sounds like doing that in the middle of a game loop would be tricky.

**Comment by camlorn** [comment]
It's not a bad idea, but I would imagine that the 99% case is that the app is just going to use the stopped event to destroy generators as needed.  Also, graceful deletion has an issue on the Synthizer side, but I forget the number of it.  being able to query that also falls into the whole "make property reads faster" thing in a way.

If you're hoping to have gapless playback, you won't get that by polling, though.

**Comment by Keithcat1** [comment]
But let's say that each enemy game has a list of generators, all connected to one source. If I recieved a stop event for one of those generators, how would I know which enemy it belonged to in order to remove it?

**Comment by ultrasound1372** [comment]
Well surely you'd either get some generator ID or a pointer or something to identify the generator that fired it.

**Comment by camlorn** [comment]
You either maintain a mapping yourself, or you put the thing that fired it in a userdata pointer.

It's not hard to make a map of synthizer object to thing that spawned it in your engine (e.g. Python's WeakKeyDictionary for instance).  By not very hard I mean maybe 20 lines in most programming languages.  I see value in supporting some sort of polling interface eventually, but I'm not willing to do it in a one-off fashion on a case-by-case basis because that slowly turns into a maintenance burden, and I don't have the bandwidth to prioritize the optimization work that needs to happen to make that possible when it's almost trivial to implement yourself.

**Comment by Keithcat1** [comment]
How about something where you create a generator, attach it to a source, and tell Synthizer to drop it when it's done playing and just forget it? That should work for cleaning up sounds like gunshots and footsteps.

**Comment by camlorn** [comment]
That's #24

**Comment by camlorn** [comment]
The event system has landed, but with constraints and with planned changes in 0.9.  I'm leaving this issue open until 0.9 happens which will improve the story around multithreaded management of handles.  BufferGenerator and StreamingGenerator both now send a finished and looped event, which are sufficient to be used in a variety of scenarios.  Specifically, we're also careful to send finished if the node is finished and looping gets set to false, which enables graceful deletion.  Specifically:

To gracefully delete a non-looping generator:

- Create the generator.
- Record it somewhere so you can tell which one it is
- Add it to the source
- Destroy it when you get a finished event.

This recipe also works for looping, as long as the generator is configured to loop before being attached to the source.  The next release will probably be sometime later today; I'm also going to try to get one more thing into it.

@chrisnorman7 
I think this solves your Earwax deleting issues for the short term.  In the long term Synthizer itself will still be implementing graceful deletion.  As one of the early adopters, let me know if it doesn't.

**Comment by chrisnorman7** [comment]
Will do mate. Thanks for that

Where the docs for this be? I'm guessing it'll be as obvious (in Python) as:

```python
generator.finished = f
```

But in case I'm wrong, I'd rather read the manual than get you to repeat yourself.

**Comment by camlorn** [comment]
I'm probably late to this party but there's a tutorial up on synthizer.github.io.

**Comment by chrisnorman7** [comment]
Haha, yeah, found it ages ago.

Good job though.

Take care,

Chris Norman

**Comment by ahicks92** [comment]
This should now be closed out.  Will land fully in 0.9.  I'm going to be doing a final code audit to check some things in general before pushing 0.9 out, but there's no reason to keep this open.

If you're a Python user nothing has changed for you.  C users will have minr incompatibilities in 0.9, namely that you're now supposed to deinit event structs when you're done with them.
