### ISSUE TITLE
Graceful deletion of objects without audio artifacts

### ISSUE THREAD

**Issue by ahicks92** [synthizer/synthizer#24]
We need to have an API which allows for as much of the following as we can get:

- Deleting an object, but only after it's faded out for a block or two.
- Deleting an object, but only after it's gone silent.
- Deleting an object, but only after it has "finished", for example a non-looping BufferGenerator.
- Deleting an object, and also keeping other related objects around, for instance buffers attached to generators.

I don't have a design in mind yet.  We'll probably borrow the WebAudio model where we model this as an internal reference to the same object: deleting will immediately hide the C handle, but the object itself will hold a `shared_ptr` to itself.

**Comment by Keithcat1** [comment]
Can we have a way to mark a generator to be freed when the source it's connected to is destroyed?

**Comment by camlorn** [comment]
I haven't designed this API in detail yet, and I haven't yet planned out all of the interaction models that it will support.  What is the use case you're concerned about me not covering?

Broadly speaking the goal here is to just let you let go of all the objects involved because you don't care.  It sounds like what you are proposing is an interface that basically just stops downstream consumers from having to maintain a struct containing a few handles rather than one, which would just promote bad programming practice more than anything.  It'd also require mutexes and such on the Synthizer code paths which need to be threadsafe, whereas whatever engine is using Synthizer can be as un-threadsafe as it wants.

**Comment by ahicks92** [comment]
Ok.  This is called lingering and will land in 0.9.  In Python:

```
myobj.configure_delete_behavior(linger=True)
```

Optionally, you can also pass `linger_timeout=seconds` to bound how long it will linger for.

Generators either fade themselves out in a way which won't click or stay around until they're finished, e..g at the end of the buffer. Sources stay around until they don't have generators.  Effects will shortly linger until they're silent when possible, e.g. reverbs until after their t60.
