### ISSUE TITLE
reverb.input_filter_enabled = false silences reverb

### ISSUE THREAD

**Issue by chrisnorman7** [synthizer/synthizer#34]
Hi,
It seems if you set `GlobalFdnReverb.input_filter_enabled = False` when it is already `False`, you get silence.

I have written minimal code:

```python
from time import sleep

from synthizer import initialize, Buffer, BufferGenerator, DirectSource, Context, shutdown, GlobalFdnReverb

initialize()
c: Context = Context()
s: DirectSource = DirectSource(c)
g: BufferGenerator = BufferGenerator(c)
g.buffer = Buffer.from_stream('file', 'sound.wav')
s.add_generator(g)
g.looping = True

r: GlobalFdnReverb = GlobalFdnReverb(c)
c.config_route(s, r)

sleep(1)
r.input_filter_enabled = False
sleep(1)
shutdown()
```

Is it something I'm doing?

**Comment by camlorn** [comment]
It defaults true. If the above example code breaks as-is, then it's just setting it to false in general. I'll investigate this weekend but it will be blocked on the 0.7.8 fiasco.

**Comment by camlorn** [comment]
I found the bug in this, but I'm going to be killing the properties in 0.8 probably sometime in the next week.  I'd just stop using them for the time being.

We're going to get a proper filter property type instead, but I'm trying to make 0.8 be the big release that breaks compatibility rather than do that in 4 or so releases in a row.  I'll be tweaking interfaces before things that the interfaces are for are entirely extant, but as a Python user you shouldn't have to care save for these specific two properties.
