### ISSUE TITLE
Implement the Ogg decoder, if possible

### ISSUE THREAD

**Issue by thgcode** [synthizer/synthizer#37]
Hi,
Since there is a stub in src/decoders/ogg.cpp and a reference to stb_vorbis.c in src/single_file_libs.c, I created this issue to track the Ogg decoder support. I would like to ask if you still are planing to implement it?
Thank you!

**Comment by camlorn** [comment]
It's possible, but it requires forking stb_vorbis which is why it hasn't been done.  This is probably post-1.0, but we have a public domain MP3 decoder and MP3 in general is now patent free, or at least patent free enough.

The specific problem is that stb_vorbis only supports files, so it can't integrate with the streaming infrastructure, and the callback interface it does have is overcomplicated and maybe doesn't provide sample accurate seek while the file one does.

**Comment by Keithcat1** [comment]
I think a dr_vorbis library is in the works. Not ready yet though, but
there's an issue on the dr_libs repository somewhere.

**Comment by thgcode** [comment]
I'll try to fork it to see how I can implement the callbacks... if it works I'll post here

**Comment by camlorn** [comment]
@thgcode 
basically, you have to find all the references to `file *` and replace them with some sort of wrapper struct that contains callbacks along the lines of what Synthizer does with dr_mp3/dr_wav.  Unfortunately that library is rather large and not abstracted super well.  I can't say what the effort is because it seemed more worth it to move on once MP3 was working.

@Keithcat1 
Did it have recent updates?  I looked at it, but it was basically super alpha and updating really slowly.  He makes good libraries, though.

**Comment by thgcode** [comment]
I also thought it would be more difficult, but I added a callback... there aren't much changes to be made because the reading of files are done on wrapper functions. I'm creating the Ogg decoder and  will test if it works.

**Comment by camlorn** [comment]
I'll be happy to review a PR for it and to provide guidance, but in terms of integrating your fork into the core library and etc I have bigger core library fish to fry if I'm going to actually have to do the coding for it right now, so you'll need to give me something completed.  As some points to get you started:

I'm fine using the callback interface that does exist, as long as it turns out that the really weird seeking algorithm it wants you to use is sample-accurate, so if you want to dig around in there and find out whether that's the case, feel free.  In general I'd rather avoid forking, but in this case it seems worth it.

The sample-accurate seek point is super important.  It opens up use cases like sample accurate looping over encoded assets.  One of the reasons I chose that library is because it has support for this, so whatever happens we need to not lose that support.

I'd suggest a top-level directory `forked_third_party/stb_vorbis/bla` or similar.  For all the other third party dependencies, I can do a bit of git cloning and file surgery to update them, and it'll be easy to lose the fork if we put it in the same place.

It's worth keeping in mind that Synthizer streams don't always support seek.  They all do at the moment because it's only files, but the framework is abstracted to make that optional, so your callback will probably either need to be optional as well, or able to return errors.

Given the scope of this and the fact that a C dependency is being forked it would be best to run it under address sanitizer.  This is particularly easy on Linux or under WSL, but I can dig up Windows instructions provided that you've got Clang 10 or later.  Ubsan would also be good, but I think there's probably a lot of other Synthizer noise with that one because I haven't yet been seriously running it myself.

**Comment by thgcode** [comment]
To complicate things, I discovered that newer STB_vorbis has bugs decoding some files (the ones I was testing). The version included in Synthizer doesn't have these bugs but we'll be locked on a specific version of STB_vorbis. I'll try to reimplement the callbacks on the Synthizer version to see if it works.

**Comment by thgcode** [comment]
I managed to make it work.
I won't create a PR right now because I need to test it some more and add documentation to the function I added on stb_vorbis and make it more organized.
For people that want to compile and test it, here's the link to my branch:
HTTPS://github.com/thgcode/synthizer/tree/ogg-support

**Comment by camlorn** [comment]
Do you have links to upstream stb_vorbis issues with more info?

Does running your files through ffmpeg fix them?

If the answer is no to the first and yes to the second I'm against pinning to an old stb_vorbis and would rather just document the procedure.  At the end of the day we *do* have MP3, and as far as I know that works.  If we didn't have a working lossy codec, fine, but given that we do I really don't want this to turn into a maintenance headache.  Frankly, I don't have the expertise to maintain or improve stb_vorbis because it's a super specialized area and even testing it needs a giant corpus of content with the original files to try it against.

This library isn't for general purpose media players or something.  I personally have no objection telling people "Use MP3" or "run your files through this script" or "use this encoder" or what have you if it comes to it.  I think my primary question at the moment is whether the files you have are in some way special.  It'd be good to not lose the support for apps to be like "now plug in your audio file" and I know that there are some obscure features of ogg that aren't really used by modern decoders, so maybe this can be easily solved if we rule those out.

**Comment by thgcode** [comment]
There's a issue and a PR at HTTPS://github.com/nothings/stb/issues/1063 . Maybe for now the best is, as you say, just use mp3 until the problems on the library are resolved. I'll close the issue for now and wait if they merge the PR.

**Comment by camlorn** [comment]
In the worst case, I can eventually offer an optional dependency on libvorbis, and those who want this can take the hit of having a BSD-licensed dependency in the stack.  BSD isn't the end of the world, it's just a goal of this library to be as public domain as possible since I've done a few of these now and the lack of quality audio code out there is basically nonexistent outside closed-source commercial solutions.

Thanks for the link and looking into this.  While the conclusion is disappointing for the time being, you actually just saved me a lot of time.  You'll have a solution of some sort eventually, just don't know what that's going to look like yet.
