### ISSUE TITLE
Allow retrieving weather an object is paused

### ISSUE THREAD

**Issue by Keithcat1** [synthizer/synthizer#42]
This makes it easier to  just toggle weather something is paused or not with one line of code, instead of keeping track of when something is paused manually and using that.

**Comment by camlorn** [comment]
Anything that starts with "retrieve whether" runs into the state latency issues.  A call to `syz_pause` followed immediately to a call to a hypothetical `syz_isPaused` can return false.  Additionally, if you're connecting this to a UI or something, you need the flag in your code so that the UI can see it.

Ergonomics is is the second thing on the priority list when it comes to goals of the library.  The first can be phrased as something along the lines of "don't expose an API that lets users get it wrong" with a side salad of "don't expose an API that forces an inefficient or complex internal design".  To that end, I won't be offering this.  With respect to getting it wrong, you should never use any audio library as a source of truth for your app for a whole variety of reasons.  With respect to efficiency and complexity, I'm not willing to special case pausing outside the normal command queue architecture, which is what this would take.
