### ISSUE TITLE
When destroying a source more than once, Synthizer now raises KeyError instead of ``SynthizerError

### ISSUE THREAD

**Issue by chrisnorman7** [synthizer/synthizer#47]
Previously when a source was destroyed twice, a nice ``SynthizerError`` was raised. Now it's ``KeyError``.

```bash
Python 3.9.1 (tags/v3.9.1:1e5d33e, Dec  7 2020, 17:08:21) [MSC v.1927 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from synthizer import *
>>> initialize()
>>> c = Context()
>>> s = DirectSource(c)
>>> s.destroy()
>>> s.destroy()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "synthizer\synthizer.pyx", line 210, in synthizer._BaseObject.destroy
  File "synthizer\synthizer.pyx", line 190, in synthizer._unregister_object
  File "synthizer\synthizer.pyx", line 191, in synthizer._unregister_object
KeyError: 0
```

**Comment by camlorn** [comment]
I'll make it raise RuntimeError, but just don't destroy things twice.  You really probably shouldn't have been doing that in the first place, if you were.

**Comment by chrisnorman7** [comment]
I was, and catching the errors.

Take care,

Chris Norman

**Comment by camlorn** [comment]
That's really bad programming practice in general.  Most libraries like Synthizer will flat out crash the process if you do that, and Synthizer may do so as well in the future.  I am actually planning on moving us to a reference counted scheme and making Synthizer objects value types, which will go extra poorly with this sort of approach.  You should learn how to manage the lifetime of your objects properly, rather than rely on this behavior. At the moment, I don't believe that there is any Synthizer error that isn't effectively fatal or due to programmer error, save perhaps errors decoding from disk.

Given that I know what you're working on, you may want to look at Python's weakref module or something.  But also given that I know what you're working on, whatever place lead you down this path is probably going to be problematic for users, as this implies that objects can be leaked.  99% of the time, leaking the object is going to take a CPU and ram hit, while likely still producing audio.

**Comment by chrisnorman7** [comment]
You're right of course. I was going for Python's "better to ask for
forgiveness than permission" thing, but you're right: It's something I
should work on.

The whole lifecycle thing is something I can't quite get my head around. I
mean I know what it is, but how to implement it with something like
Synthizer: Do you create a new source for each sound you play and
sacrifice the chance to put reverb on one source and have everything
change? Also if you do that, if one object moves, it aurally drags
everything else with it. Or do you let ever sound have its own source, and
work that way?

I'm leaning more towards option 2, but it's definitely something I need to
think about.

Take care,

Chris Norman

**Comment by camlorn** [comment]
You're supposed to use Synthizer and most other libraries like it by having every sound that logically needs to move together share the source.  You'll want to make something like a SourceFactory that can pull them out and hook them up to the proper reverb sends.  The best way to deal with this sort of thing is to apply MVC (that is, your game objects don't know about Synthizer at all and something else "reaches in" to figure out what to do and/or you send play-a-sound commands). but failing that, something like this will be closer to what you want:

- Sources come from a SourceManager and get returned to the SourceManager when they're ready to be destroyed.
- The SourceManager knows how to hook sources up to effect sends and set defaults on creation.
- The SourceManager gets asked to move sources around, and figures out if the effect sends need to change.

In practice SourceManager would return some sort of stripped-down wrapper that's got some functions on it instead of a Synthizer source that call out to the manager: "Hey, the user moved me" or whatever

In general you need to develop higher level abstractions on top of Synthizer to use synthizer effectively.  I would offer them but they end up being pretty engine specific.  It's entirely reasonable to expose a Source class that isn't actually a Synthizer Source which backs onto a bunch of custom machinery for managing the Synthizer one, and if you're using an object oriented design for your stuff that's actually exactly what I'd expect/do myself.

**Comment by chrisnorman7** [comment]
OK, thank you for the tips.

Take care,

Chris Norman

**Comment by camlorn** [comment]
This is now wontfix I'm afraid.  0.9 is going to crash your process outright because it's going to be able to finally get rid of the internal data structures that let Synthizer track handles in a way which can expose this error.  Good memory and performance improvements there, but bad for what you want to be able to do.
