### ISSUE TITLE
Increase the "width" of FdnReverb

### ISSUE THREAD

**Issue by Ghorthalon** [synthizer/synthizer#58]
Hi,

I might just be misunderstanding something in regards to how the FDN Reverb actually works, but here's my situation.
If you add an FDN Reverb to a sound, the first reflection plays the sound almost unaltered in the center of the stereo field. This can cause phasing issues if your SYZ_P_LATE_REFLECTIONS_DELAY is set very small (for example to 0), or weird phasing/flanger effects if it's something slightly bigger. Additionally, since the sound is also played from the center of the stereo field, this clashes with the HRTF panning which makes it harder to understand where the sound might be coming from, especially when you're far away from the sound or the reverb is louder than the sound itself.
I usually do set the delay to 0 at the moment, since it's preferable to the odd flanger-like effect that you get from introducing the same sound at a very small delay in my opinion.
I wonder if this could be fixed or if there's a workaround, or if I'm just using the effect wrong? Ideally what I'd like to happen is to skip that first reflection so that I get the space from the reverb without that first repetition in the center.

**Comment by ahicks92** [comment]
You shouldn't be setting that delay to zero: that's highly unrealistic.  I'd try 0.03 or so.  Delays as small as you're using will pretty much always produce phaser-like effects.  For perspective, 30 ms is the delay to a 10 meter wall away (that is, these values are higher than people generally think they are).  Also, pull back the gain to 0.5 or less.  These two together probably give you a pretty immediate improvement.

I'm going to be tweaking that default, as well as giving you an input filter to cut off the higher frequencies, both of which should help.

I noticed the panning problem yesterday.  It's quite hard to fix being as a lot of the alternatives here end up panning the sound to one side or the other instead, but something can definitely be done about it even if I don't know what at the moment.  The reverb should really be "wider", too.

**Comment by ahicks92** [comment]
Ok, so playing with this.  A few lines of this won't be released for a week or two so ignore the `syz_initRouteConfig` and the filters.  Mostly putting this here for my reference.  The following seems to give a quite good reverb:

```
	CHECKED(syz_initRouteConfig(&route_config));
	CHECKED(syz_createGlobalFdnReverb(&effect, context));
	CHECKED(syz_setD(effect, SYZ_P_LATE_REFLECTIONS_DELAY, 0.03));
	CHECKED(syz_setD(effect, SYZ_P_MEAN_FREE_PATH, 0.1));
	CHECKED(syz_setD(effect, SYZ_P_T60, 0.3));
	CHECKED(syz_setD(effect, SYZ_P_GAIN, 1.0));
	CHECKED(syz_biquadDesignLowpass(&filter, 1500, 0.7));
	CHECKED(syz_setBiquad(effect, SYZ_P_FILTER, &filter));
	CHECKED(syz_routingConfigRoute(context, source, effect, &route_config));
```

`CHECKED` is a macro, ignore it.  If you just set all the properties but filter you'll probably be much happier, as a starting point for this, but filter will be available in the next release and improves it a lot.  It will be defaulted--you don't have to do anything but wait.  The C side is almost done but I have to write a manual and bind it to Pythonand stuff like that so it's not going to be out this weekend.

Also feel free to work on presets.  If you find settings you like post them here or e-mail me or something.  We don't have presets because designing them takes time and can be done by users so I haven't bothered yet.

**Comment by ahicks92** [comment]
I just put the default changes on the 0.9-dev branch.  They'll land in 0.9.  It's much better than what it used to be.  This will close out when that lands on master.  That's not to say that there's not more improvements coming, just that this specific issue is resolved.  Though admittedly more improvements will probably be after 1.0.
