### ISSUE TITLE
It's no longer possible to download DLLs for Windows on the release page

### ISSUE THREAD

**Issue by Keithcat1** [synthizer/synthizer#69]

**Comment by ahicks92** [comment]
This isn't going to be supported because it's not worth it to me to maintain at least 4 variants of the dll, arguably as many as 8, to match up with the possible various MSVC configurations.  If you want this you'll need to build it yourself.  If I've got documentation somewhere which claims this is doable, then feel free to reopen, but this is intended behavior.
