### ISSUE TITLE
The `scalar value on `PannedSource` doesn't work reliably

### ISSUE THREAD

**Issue by chrisnorman7** [synthizer/synthizer#76]
I have found the below code only works about half of the time:

```python
from synthizer import *
from time import sleep
with initialized():
  context = Context()
  left = PannedSource(context)
  generator = BufferGenerator(context)
  generator.buffer = Buffer.from_file('ziggurat_examples/ratcatcher/sounds/weapons/aim.mp3')
  generator.looping = True
  left.add_generator(generator)
  print(left.panning_scalar)
  left.panning_scalar = -1.0
  sleep(1)
  print(left.panning_scalar)
  sleep(3)
  generator2 = BufferGenerator(context)
  generator2.buffer = Buffer.from_file('ziggurat_examples/ratcatcher/sounds/weapons/shoot.mp3')
  left.add_generator(generator2)
  left.panning_scalar = 1.0
  sleep(3)
```

This is with both the latest code from PyPi, and with my Dart bindings which use the latest C++ source from the master branch.

**Comment by Keithcat1** [comment]
I've also noticed this. Was going to make an issue for that but
apparently the problem with a todo list is that you relie on it, so if
something gets lost in there you'll never find it again.
Seems related to #51 and #52. I guess the problem was never fully
fixed or this is something new.

**Comment by chrisnorman7** [comment]
Haha, brilliant!

Didn't realise I'd already opened an issue on an identical subject.

Thanks,

Take care,

Chris Norman

**Comment by ahicks92** [comment]
Interesting.  Will either of you be disappointed if we just grow a `ScalarPannedSource`?  This apparently is going to come back to haunt me for all time otherwise.  Thus the consequences of early bad decisions, I suppose.

**Comment by chrisnorman7** [comment]
Suits me mate.

Take care,

Chris Norman

**Comment by Keithcat1** [comment]
Sure why not? It's not like you can use both a scalar and azimuth /
elevation on the same source anyway.

**Comment by ahicks92** [comment]
Ok, done.  We now have `AngularPannedSource` and `ScalarPannedSource`.  Additionally, you have to pass the panner strategy up front (no more changing it after the source is created) and you also have to pass initial values for whatever the panning properties are.  The latter should be convenient for anyone in a higher level language with default keyword arguments, but more importantly I suspect there might be one more bug out there and that will let me squash it without having to go nuts and break the API.

Note that `SYZ_PANNER_STRATEGY_DELEGATE` is new and should be your default so that you can still respect `SYZ_P_DEFAULT_PANNER_STRATEGY` on the context.  The intent is that you don't use other values there unless you want to override the context, and just set the context to your most common need (in the future this will probably become more interesting because the context will autodetect surround sound once we start doing that).

I'll close this out after someone confirms it's all good now.  It seems to be here.  I'll push it in the 0.11 release along with automation; we can bump automation to 0.12 if someone else complains and we need to push it faster, but afaik both of you are building from/willing to build from master anyway and automation is almost done.
