### ISSUE TITLE
Occasional crashes when getting data relating to buffers

### ISSUE THREAD

**Issue by chrisnorman7** [synthizer/synthizer#77]
Hi,
I'm trying to track down a bug that is coming up when I calculate the size of buffers.

Firstly I thought it was something to do with my code, but getting channel counts and length in samples seems to crash as well. There's no Synthizer errors, it just crashes.

Trying to reproduce the bug does nothing, I can get as many properties as I like, but there is definitely something there.

The tests aren't running in parallel or anything, so it's nothing like that.

Is any of this ringing any bells? Or can you think of anything I could do to track down the crash?

Thanks in advance.

**Comment by ahicks92** [comment]
The obvious thing to try is a simple infinite loop that does the code which you think crashes repeatedly and see if it crashes.

Drop `-DCMAKE_BUILD_TYPE=Release` from your building command line and you will get a debug build, which can sometimes provide more info because it compiles in the asserts (if those fail they either show up in stdout on the terminal or in message boxes).

can you find out if it's machine specific?  Your description implies that you're running it in a testing framework with a bunch of other unit tests; can you find out what happens if you run the failing test in isolation?

The easiest way to do this without Synthizer being bugged is to accidentally use a handle after deletion: as the error related to that says we can only catch some cases.  Being as I know you, that doesn't seem like an error you would make at this point.

If you can figure out how to run address sanitizer that's often the best thing to do, but I'm not sure how to do that in your case.  You can (try to) get Synthizer to compile it in by opening CMakeCache.txt, finding CMAKE_C_FLAGS and CMAKE_CXX_FLAGS, and adding `/fsanitize=address` to both.  See [here](https://docs.microsoft.com/en-us/cpp/sanitizers/asan?view=msvc-160) for official MSVC docs on that.  I wouldn't spend too much time on this option yet: it is generally the most useful, but it's also generally very hard for people who don't know low-level stuff to get working, and we might have to try to find the Windows equivalent of `LD_PRELOAD` in order to make it play nice with the Dart VM (if you're wondering why we bother, this is the C++ thing that gives you Python-quality errors for all of the standard "oops I shot myself because it's C++" cases, at least in debug builds, but it can be obscure enough that the uninitiated may not be able to chant the magic incantations to the programming gods).

**Comment by chrisnorman7** [comment]
Nope... Apparently it's me being an idiot.

I could have sworn that `1024 ^ 3) would give me a GB, but apparently it's a bitwise operator or some such. I was in fact reading from invalid handles, a fact which I would probably have recognised if I'd thought to check every value.

Sorry for the panic.

**Comment by ahicks92** [comment]
Ah yeah, ^ is bitwise xor.

**Comment by chrisnorman7** [comment]
Hehe, I know that now. Kind of miss Python's ** operator. :(

Take care,

Chris Norman
