### ISSUE TITLE
Add method for getting context defaults without a context

### ISSUE THREAD

**Issue by ndarilek** [synthizer/synthizer#85]
I'm trying to do something like this in my Bevy plugin:

```
#[derive(Clone, Copy, Debug)]
pub struct SynthizerConfig {
    pub default_panner_strategy: syz::PannerStrategy,
}

impl Default for SynthizerConfig {
    fn default() -> Self {
        Self {
            default_panner_strategy: syz::PannerStrategy::Stereo,
        }
    }
}
```

I'd like to make more defaults configurable. Unfortunately, as implemented, I'd need to check the docs for each field I'd like to make configurable to determine the default value. I'd also need to keep these values in sync across Synthizer changes.

Wondering if it might make sense to store context defaults in global consts or something similar? Then both my config struct and the context itself can pull defaults from the same place, and they'd be synced across future changes.

Thanks.

**Comment by ndarilek** [comment]
> Why not just use Option and set the ones which are set to some(val)?

I guess I can do that for now. If it's possible to change those at runtime, though, then what I'd hoped to do was make changing the config resource the Bevy API for changing these parameters, then have a system that syncs resource changes to the context. Would it be easier to add a method on properties that restores them to their default value, assuming one is possible? Then `None` could be equivalent to Synthizer defaults, and changing the value to `None` on my side would just restore the default and not have to care what that was?

And no, it doesn't have to be const.

Thanks.

**Comment by ahicks92** [comment]
You can't change the property defaults at runtime in the sense of generically changing what some property will be for all new objects of that type, nor do I ever intend to allow that.  You can "change" the defaults for some special cased properties on sources, but this is actually just copying them down from a context, not actually changing the defaults.  Also, copying them down like that was probably a bad idea--changing it won't happen soon but is in the back of my mind as something I want to work on.

What stops this from being const is that short of doing everything as actual literal constants in the header, which requires exposing my xmacro private headers to you, no language is going to understand that it can/should access at compile time because the linker is too late.

Also, reminder that property changes don't show up immediately if you read the property right after.  This really just adds motivation for getting some story here but is worth noting if you're going to try to have a bidirectional sync.

I'll think about this but I really want to get higher impact things out the door.  in theory we have impressive stuff coming down the pipeline that I haven't bothered to open issues for.

**Comment by ndarilek** [comment]
Hang on, so just to confirm, if I do something like this in a system:

```
    if config.is_changed() {
        context
            .default_panner_strategy()
            .set(
                config
                    .default_panner_strategy
                    .unwrap_or(defaults.panner_strategy),
            )
            .expect("Failed to set panner strategy");
// same for distance_model, distance_ref, distance_max, rolloff, closeness_boost, and closeness_boost_distance defaults
```

that won't change panner_strategy for any new sounds I create? I'm not interested in property reads being frame-accurate, nor do I need the change to happen in the same frame.

For now I'm just reading defaults for all of those on startup, stashing those in a private resource, and using that to restore defaults should the config value be noned out.

**Comment by ahicks92** [comment]
I'm going to be refactoring the whole library, and contexts are going to stop being the be-all end-all.  No real point in doing this when the thing it's for is getting majorly changed at some point. Though who knows when; me and free time are not friends.
