### ISSUE TITLE
Sound glitching through SteelSeries headphones

### ISSUE THREAD

**Issue by chrisnorman7** [synthizer/synthizer#88]
Hi,
I'm trying to play the attached sound with Synthizer, and whether I play it from a string, a normal buffer generator, or stream it with a streaming generator, it distorts really badly, but only when listening through my SteelSeries Arctis Nova Pro Wireless headset.

When played through my Motu M4 USB C sound card, it's fine.

The headset is connected through its dedicated sound card, which is hooked up with a USB A to C cable, so I'm *not* using the Bluetooth connection.

I'm using the latest Synthizer, 0.1.9, which I compiled myself with the standard CMake instructions, under Windows 11.

Thanks in advance.

**Comment by chrisnorman7** [comment]
Sorry, don't think the file got uploaded. I've created a [Dropbox transfer](https://www.dropbox.com/t/xIGsN4nGQc9jVlmH) for it.

**Comment by chrisnorman7** [comment]
So apparently this only comes up when I'm using the SteelSeries Sonar thingy, and not just the default driver. Doesn't matter which output I use with Sonar, and it's only some sounds which are affected.

**Comment by ahicks92** [comment]
This is almost certainly something against miniaudio if it's my fault at all.  I think miniaudio has example programs that play files.  Can you figure out building those and try?

Miniaudio is here: https://github.com/mackron/miniaudio

**Comment by Keithcat1** [comment]
You can build such a program like this:
Open visual studio developer tools command prompt:
```
git clone https://github.com/mackron/miniaudio
cd miniaudio\examples
cl simple_playback.c
simple_playback my_sound.{mp3,flac,wav}
```

**Comment by chrisnorman7** [comment]
Thanks @Keithcat1, I did not know that.

Sorry @ahicks92, but now I've followed @Keithcat1's instructions, I can confirm that miniaudio doesn't glitch on the files, while Synthizer still does.

**Comment by ahicks92** [comment]
I've done some investigating and I think this is some sort of miniaudio bug. I don't yet have enough information to say what.  We request the default sample rate of the device and resample ourselves, which is supposed to be fine.  Specifically:

- Sample rate of sonar is 96000. Channels 8.
- Sample rate of synthizer is 44100, always outputs 2 channels for now.
- Request default sample rate from miniaudio and apply conversion ourselves fails.
- Request 95999 sample rate from miniaudio engages the miniaudio resampler and works. So:
  - Our resampler runs 44100->95999.
  - Miniaudio resampler runs 95999 to 96000.
- Hardcode miniaudio to 95999 as above, then hardcode our resampler to 96000 also works (in this case being off by 1 sample is negligible).
  - This indicates that it is unlikely to be on our side.  Could still be, but is unlikely.

I cannot quickly spot the difference.  I can tell that the issue is at the "edge" of a block because if we raise the block size of Synthizer, then the glitching slows down.  My suspicion is that everyone using miniaudio uses the resampler-engaged paths, and we are hitting both "I want to do the resampling myself" and some extreme values all at the same time.  I'll have to spend more time on this, but am out of time/energy for this weekend.

**Comment by chrisnorman7** [comment]
@ahicks92 Thank you so much for spending time on this, it's very much appreciated.

**Comment by ahicks92** [comment]
All right. I actually found this.  The bad commit is d7d0a3371e715940896a04b682bbba7ffa90373c.

What I think is going on is as follows:

- We set our latencies lower than what Steel Series can handle, but higher than the defaults. This is good: the defaults, on a low-latency device may or may not be too low.
- Steel Series goes "cool, fine, by the way my minimum latency is a sample" or something like that.
- Miniaudio goes "cool, let's go" and respects our values, since Steel claims they're fine.
- But they're not, haha, sorry.  And then we explode.

Which is why I don't like (or suggest) that people use weird software enhancement packages, though admittedly this can occur in hardware too.  It looks like just asking Miniaudio to use defaults again is fine.   I don't like that, but I don't think that changing this will break System Fault 

@chrisnorman7 are you using something where it's easy for you to try master? I pushed a commit that should do the trick.

CC @ndarilek because this will eventually make its way to Rust and when it does, system fault weirdness should probably be reported if that comes back. But (as I said above) I don't think it will.

**Comment by chrisnorman7** [comment]
Hi,
Thanks @ahicks92, that works perfectly. I really hope it doesn't mess anything up for other people!

**Comment by ahicks92** [comment]
I'll roll it out to Rust later today. If folks want it in Python then they can volunteer.

**Comment by ahicks92** [comment]
While I remember there was another bug with the config: periodSizeInFrames is in the device sample rate. So our value was in practice variable and too small anyway.

We could technically set periodSizeInMilliseconds or something but I'm not touching this for now. I forgot to do the rollout, I'm afraid, so you'll get that this weekend.
